version: '2'
services:
    slapd:
        image: opendicom/slapd-for-dcm4chee:5.21.0
        ports:
            - "389:389"
        environment:
            LDAP_BASE_DN: dc=dcm4che,dc=org
            LDAP_ORGANISATION: dcm4che.org
            LDAP_ROOTPASS: secret
            LDAP_CONFIGPASS: secret
            DEVICE_NAME: dcm4chee-arc
            AE_TITLE: DCM4CHEE
            DICOM_HOST: localhost
            DICOM_PORT: 11112
            HL7_PORT: 2575
            SYSLOG_HOST: localhost
            SYSLOG_PORT: 8514
            STORAGE_DIR: /storage/fs1  # dicom storage dir
